server:
  port: 8190
spring:
  application:
    name: front-service
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
#ribbon:
#  eureka:
#    enabled: true
